# Generated by Django 5.0.4 on 2024-05-19 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaran', '0009_alter_tableonline_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('price_type', models.CharField(choices=[('$', 'USD'), ("So'm", 'UZS')], default="So'm", max_length=30)),
                ('image', models.ImageField(upload_to='media/product')),
                ('reyting', models.IntegerField()),
                ('kg', models.IntegerField()),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaran.turi')),
            ],
        ),
    ]
