# Generated by Django 5.0.4 on 2024-05-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaran', '0010_turi_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Mahsulot',
        ),
    ]
