# Generated by Django 5.0.4 on 2024-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaran', '0011_rename_product_mahsulot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['subject']},
        ),
        migrations.AlterModelOptions(
            name='costumer',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='foodmenu',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='masterchef',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['type_name']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='tableonline',
            options={'ordering': ['ism']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['description']},
        ),
        migrations.AlterModelOptions(
            name='turi',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['subject'], name='restaran_co_subject_d8063f_idx'),
        ),
        migrations.AddIndex(
            model_name='costumer',
            index=models.Index(fields=['last_name', 'first_name'], name='restaran_co_last_na_3b4dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='foodmenu',
            index=models.Index(fields=['title'], name='restaran_fo_title_362cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='mahsulot',
            index=models.Index(fields=['name'], name='restaran_ma_name_64db1c_idx'),
        ),
        migrations.AddIndex(
            model_name='masterchef',
            index=models.Index(fields=['last_name', 'first_name'], name='restaran_ma_last_na_650b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='producttype',
            index=models.Index(fields=['type_name'], name='restaran_pr_type_na_74cfcb_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['title'], name='restaran_se_title_e7116f_idx'),
        ),
        migrations.AddIndex(
            model_name='tableonline',
            index=models.Index(fields=['ism'], name='restaran_ta_ism_6c1f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['description'], name='restaran_te_descrip_4a4256_idx'),
        ),
        migrations.AddIndex(
            model_name='turi',
            index=models.Index(fields=['name'], name='restaran_tu_name_ca3d4c_idx'),
        ),
    ]
