# Generated by Django 5.0.4 on 2024-05-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_savat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savat',
            old_name='product_id',
            new_name='product',
        ),
    ]
