# Generated by Django 5.0.4 on 2024-05-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_product_id_savat_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savat',
            old_name='product',
            new_name='product_id',
        ),
    ]
